/**
 * Language Context - REIKI ENERGY
 * Manages multi-language support (English, Hindi, Tamil, Telugu, Bengali)
 */

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'ta' | 'te' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  // Translation function
  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];

    for (const k of keys) {
      if (value && typeof value === 'object') {
        value = value[k];
      } else {
        return key; // Return key if translation not found
      }
    }

    return typeof value === 'string' ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

// Translations
const translations: Record<Language, any> = {
  en: {
    common: {
      home: 'Home',
      about: 'About Us',
      howToPlay: 'How to Play',
      faq: 'FAQ',
      contact: 'Contact Us',
      terms: 'Terms & Conditions',
      privacy: 'Privacy Policy',
      fairPlay: 'Fair Play',
      responsibleGaming: 'Responsible Gaming',
      login: 'Login',
      register: 'Register',
      logout: 'Logout',
      dashboard: 'Dashboard',
      matches: 'Matches',
      myTeams: 'My Teams',
      leaderboard: 'Leaderboard',
      profile: 'Profile',
      createTeam: 'Create Team',
      save: 'Save',
      cancel: 'Cancel',
      edit: 'Edit',
      delete: 'Delete',
      back: 'Back',
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
    },
    home: {
      title: 'Master Your Fantasy Cricket Skills',
      subtitle: 'Free-to-play educational platform. No real money. Pure skill.',
      getStarted: 'Get Started Free',
      learnMore: 'Learn More',
      whyChoose: 'Why Choose REIKI ENERGY?',
      freeToPlay: 'Free to Play',
      freeToPlayDesc: 'No entry fees, no real money. Play for learning and fun.',
      educational: 'Educational Platform',
      educationalDesc: 'Learn fantasy cricket strategies without financial pressure.',
      realData: 'Real Cricket Data',
      realDataDesc: 'Live match data from official Cricket Data API.',
      fairPlay: 'Fair Play Guaranteed',
      fairPlayDesc: 'Transparent rules and anti-cheating measures.',
      skillBased: 'Skill-Based Gaming',
      skillBasedDesc: 'Test your cricket knowledge and team-building skills.',
      community: 'Growing Community',
      communityDesc: 'Join thousands of cricket enthusiasts learning together.',
      howItWorks: 'How It Works',
      step1: 'Register Free',
      step1Desc: 'Create your account in seconds. No payment required.',
      step2: 'Select Match',
      step2Desc: 'Choose from upcoming cricket matches.',
      step3: 'Build Team',
      step3Desc: 'Select 11 players and set captain & vice-captain.',
      step4: 'Compete & Learn',
      step4Desc: 'See your rank on the leaderboard and improve your skills.',
    },
    auth: {
      emailPlaceholder: 'Enter your email',
      passwordPlaceholder: 'Enter your password',
      namePlaceholder: 'Enter your full name',
      phonePlaceholder: 'Enter your phone number',
      loginTitle: 'Welcome Back',
      loginSubtitle: 'Login to continue your fantasy cricket journey',
      registerTitle: 'Create Account',
      registerSubtitle: 'Join REIKI ENERGY and start learning',
      forgotPassword: 'Forgot Password?',
      noAccount: "Don't have an account?",
      haveAccount: 'Already have an account?',
      signUp: 'Sign Up',
      signIn: 'Sign In',
      ageVerification: 'I confirm I am 18 years or older',
      acceptTerms: 'I accept the Terms & Conditions',
      selectState: 'Select your state',
    },
    footer: {
      companyInfo: 'Company Information',
      quickLinks: 'Quick Links',
      legal: 'Legal',
      disclaimer: 'Legal Disclaimer',
      disclaimerText:
        'This platform is NOT available in Andhra Pradesh, Assam, Odisha, Telangana, Nagaland, and Sikkim. Only users 18 years and older are permitted. This is a skill-based, free-to-play platform with no real money involved.',
    },
  },
  hi: {
    common: {
      home: 'होम',
      about: 'हमारे बारे में',
      howToPlay: 'कैसे खेलें',
      faq: 'सामान्य प्रश्न',
      contact: 'संपर्क करें',
      terms: 'नियम और शर्तें',
      privacy: 'गोपनीयता नीति',
      fairPlay: 'फेयर प्ले',
      responsibleGaming: 'जिम्मेदार गेमिंग',
      login: 'लॉगिन',
      register: 'रजिस्टर',
      logout: 'लॉगआउट',
      dashboard: 'डैशबोर्ड',
      matches: 'मैच',
      myTeams: 'मेरी टीमें',
      leaderboard: 'लीडरबोर्ड',
      profile: 'प्रोफ़ाइल',
      createTeam: 'टीम बनाएं',
      save: 'सहेजें',
      cancel: 'रद्द करें',
      edit: 'संपादित करें',
      delete: 'हटाएं',
      back: 'वापस',
      loading: 'लोड हो रहा है...',
      error: 'त्रुटि',
      success: 'सफलता',
    },
    home: {
      title: 'अपने फैंटेसी क्रिकेट कौशल में महारत हासिल करें',
      subtitle: 'मुफ्त-से-खेलें शैक्षिक मंच। कोई असली पैसा नहीं। शुद्ध कौशल।',
      getStarted: 'मुफ्त में शुरू करें',
      learnMore: 'और जानें',
      whyChoose: 'REIKI ENERGY क्यों चुनें?',
      freeToPlay: 'मुफ्त खेलें',
      freeToPlayDesc: 'कोई प्रवेश शुल्क नहीं, कोई असली पैसा नहीं। सीखने और मज़े के लिए खेलें।',
      educational: 'शैक्षिक मंच',
      educationalDesc: 'वित्तीय दबाव के बिना फैंटेसी क्रिकेट रणनीतियां सीखें।',
      realData: 'वास्तविक क्रिकेट डेटा',
      realDataDesc: 'आधिकारिक क्रिकेट डेटा API से लाइव मैच डेटा।',
      fairPlay: 'फेयर प्ले की गारंटी',
      fairPlayDesc: 'पारदर्शी नियम और धोखाधड़ी विरोधी उपाय।',
      skillBased: 'कौशल-आधारित गेमिंग',
      skillBasedDesc: 'अपने क्रिकेट ज्ञान और टीम-निर्माण कौशल का परीक्षण करें।',
      community: 'बढ़ती कम्युनिटी',
      communityDesc: 'हजारों क्रिकेट प्रेमियों के साथ एक साथ सीखें।',
      howItWorks: 'यह कैसे काम करता है',
      step1: 'मुफ्त रजिस्टर करें',
      step1Desc: 'सेकंडों में अपना खाता बनाएं। कोई भुगतान आवश्यक नहीं।',
      step2: 'मैच चुनें',
      step2Desc: 'आगामी क्रिकेट मैचों में से चुनें।',
      step3: 'टीम बनाएं',
      step3Desc: '11 खिलाड़ी चुनें और कप्तान और उप-कप्तान सेट करें।',
      step4: 'प्रतिस्पर्धा करें और सीखें',
      step4Desc: 'लीडरबोर्ड पर अपनी रैंक देखें और अपने कौशल में सुधार करें।',
    },
    auth: {
      emailPlaceholder: 'अपना ईमेल दर्ज करें',
      passwordPlaceholder: 'अपना पासवर्ड दर्ज करें',
      namePlaceholder: 'अपना पूरा नाम दर्ज करें',
      phonePlaceholder: 'अपना फोन नंबर दर्ज करें',
      loginTitle: 'वापसी पर स्वागत है',
      loginSubtitle: 'अपनी फैंटेसी क्रिकेट यात्रा जारी रखने के लिए लॉगिन करें',
      registerTitle: 'खाता बनाएं',
      registerSubtitle: 'REIKI ENERGY में शामिल हों और सीखना शुरू करें',
      forgotPassword: 'पासवर्ड भूल गए?',
      noAccount: 'खाता नहीं है?',
      haveAccount: 'पहले से खाता है?',
      signUp: 'साइन अप करें',
      signIn: 'साइन इन करें',
      ageVerification: 'मैं पुष्टि करता हूं कि मैं 18 वर्ष या उससे अधिक उम्र का हूं',
      acceptTerms: 'मैं नियम और शर्तों को स्वीकार करता हूं',
      selectState: 'अपना राज्य चुनें',
    },
    footer: {
      companyInfo: 'कंपनी की जानकारी',
      quickLinks: 'त्वरित लिंक',
      legal: 'कानूनी',
      disclaimer: 'कानूनी अस्वीकरण',
      disclaimerText:
        'यह प्लेटफ़ॉर्म आंध्र प्रदेश, असम, ओडिशा, तेलंगाना, नागालैंड और सिक्किम में उपलब्ध नहीं है। केवल 18 वर्ष और उससे अधिक उम्र के उपयोगकर्ताओं को अनुमति है। यह एक कौशल-आधारित, मुफ्त-से-खेलें मंच है जिसमें कोई असली पैसा शामिल नहीं है।',
    },
  },
  ta: {
    common: {
      home: 'முகப்பு',
      about: 'எங்களை பற்றி',
      howToPlay: 'எப்படி விளையாடுவது',
      faq: 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
      contact: 'தொடர்பு கொள்ளவும்',
      terms: 'விதிமுறைகள் மற்றும் நிபந்தனைகள்',
      privacy: 'தனியுரிமை கொள்கை',
      fairPlay: 'நியாயமான விளையாட்டு',
      responsibleGaming: 'பொறுப்பான விளையாட்டு',
      login: 'உள்நுழைக',
      register: 'பதிவு செய்க',
      logout: 'வெளியேறு',
      dashboard: 'டாஷ்போர்டு',
      matches: 'போட்டிகள்',
      myTeams: 'எனது அணிகள்',
      leaderboard: 'லீடர்போர்டு',
      profile: 'சுயவிவரம்',
      createTeam: 'அணி உருவாக்கு',
      save: 'சேமி',
      cancel: 'ரத்து செய்',
      edit: 'திருத்து',
      delete: 'நீக்கு',
      back: 'பின்',
      loading: 'ஏற்றுகிறது...',
      error: 'பிழை',
      success: 'வெற்றி',
    },
    home: {
      title: 'உங்கள் கற்பனை கிரிக்கெட் திறன்களை மேம்படுத்துங்கள்',
      subtitle: 'இலவசமாக விளையாடும் கல்வி தளம். உண்மையான பணம் இல்லை। தூய திறமை.',
      getStarted: 'இலவசமாக தொடங்குங்கள்',
      learnMore: 'மேலும் அறிக',
      whyChoose: 'REIKI ENERGY ஏன் தேர்வு செய்ய வேண்டும்?',
      freeToPlay: 'இலவசமாக விளையாடுங்கள்',
      freeToPlayDesc: 'நுழைவு கட்டணம் இல்லை, உண்மையான பணம் இல்லை। கற்றல் மற்றும் வேடிக்கைக்காக விளையாடுங்கள்.',
      educational: 'கல்வி தளம்',
      educationalDesc: 'நிதி அழுத்தம் இல்லாமல் கற்பனை கிரிக்கெட் உத்திகளை கற்றுக்கொள்ளுங்கள்.',
      realData: 'உண்மையான கிரிக்கெட் தரவு',
      realDataDesc: 'அதிகாரப்பூர்வ கிரிக்கெட் தரவு API இலிருந்து நேரடி போட்டி தரவு.',
      fairPlay: 'நியாயமான விளையாட்டு உத்தரவாதம்',
      fairPlayDesc: 'வெளிப்படையான விதிகள் மற்றும் மோசடி எதிர்ப்பு நடவடிக்கைகள்.',
      skillBased: 'திறன் அடிப்படையிலான விளையாட்டு',
      skillBasedDesc: 'உங்கள் கிரிக்கெட் அறிவு மற்றும் அணி-கட்டுமான திறன்களை சோதிக்கவும்.',
      community: 'வளரும் சமூகம்',
      communityDesc: 'ஆயிரக்கணக்கான கிரிக்கெட் ஆர்வலர்களுடன் சேர்ந்து கற்றுக்கொள்ளுங்கள்.',
      howItWorks: 'இது எப்படி வேலை செய்கிறது',
      step1: 'இலவசமாக பதிவு செய்யவும்',
      step1Desc: 'விநாடிகளில் உங்கள் கணக்கை உருவாக்கவும். கட்டணம் தேவையில்லை.',
      step2: 'போட்டியைத் தேர்ந்தெடுக்கவும்',
      step2Desc: 'வரவிருக்கும் கிரிக்கெட் போட்டிகளிலிருந்து தேர்வு செய்யவும்.',
      step3: 'அணி உருவாக்கவும்',
      step3Desc: '11 வீரர்களைத் தேர்ந்தெடுத்து கேப்டன் மற்றும் வைஸ் கேப்டனை அமைக்கவும்.',
      step4: 'போட்டியிடுங்கள் மற்றும் கற்றுக்கொள்ளுங்கள்',
      step4Desc: 'லீடர்போர்டில் உங்கள் தரவரிசையைப் பார்த்து உங்கள் திறன்களை மேம்படுத்துங்கள்.',
    },
    auth: {
      emailPlaceholder: 'உங்கள் மின்னஞ்சலை உள்ளிடவும்',
      passwordPlaceholder: 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
      namePlaceholder: 'உங்கள் முழு பெயரை உள்ளிடவும்',
      phonePlaceholder: 'உங்கள் தொலைபேசி எண்ணை உள்ளிடவும்',
      loginTitle: 'மீண்டும் வரவேற்கிறோம்',
      loginSubtitle: 'உங்கள் கற்பனை கிரிக்கெட் பயணத்தைத் தொடர உள்நுழைக',
      registerTitle: 'கணக்கை உருவாக்கவும்',
      registerSubtitle: 'REIKI ENERGY இல் சேர்ந்து கற்றலைத் தொடங்குங்கள்',
      forgotPassword: 'கடவுச்சொல்லை மறந்துவிட்டீர்களா?',
      noAccount: 'கணக்கு இல்லையா?',
      haveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
      signUp: 'பதிவு செய்க',
      signIn: 'உள்நுழைக',
      ageVerification: 'நான் 18 வயது அல்லது அதற்கு மேற்பட்டவன் என்பதை உறுதிப்படுத்துகிறேன்',
      acceptTerms: 'விதிமுறைகள் மற்றும் நிபந்தனைகளை ஏற்றுக்கொள்கிறேன்',
      selectState: 'உங்கள் மாநிலத்தைத் தேர்ந்தெடுக்கவும்',
    },
    footer: {
      companyInfo: 'நிறுவன தகவல்',
      quickLinks: 'விரைவு இணைப்புகள்',
      legal: 'சட்ட',
      disclaimer: 'சட்ட மறுப்பு',
      disclaimerText:
        'இந்த தளம் ஆந்திரா, அஸ்ஸாம், ஒடிசா, தெலுங்கானா, நாகாலாந்து மற்றும் சிக்கிமில் கிடைக்காது. 18 வயது மற்றும் அதற்கு மேற்பட்ட பயனர்கள் மட்டுமே அனுமதிக்கப்படுகிறார்கள். இது ஒரு திறன் அடிப்படையிலான, இலவசமாக விளையாடும் தளம், உண்மையான பணம் இல்லை.',
    },
  },
  te: {
    common: {
      home: 'హోమ్',
      about: 'మా గురించి',
      howToPlay: 'ఎలా ఆడాలి',
      faq: 'తరచుగా అడిగే ప్రశ్నలు',
      contact: 'సంప్రదించండి',
      terms: 'నిబంధనలు మరియు షరతులు',
      privacy: 'గోప్యతా విధానం',
      fairPlay: 'ఫెయిర్ ప్లే',
      responsibleGaming: 'బాధ్యతాయుత గేమింగ్',
      login: 'లాగిన్',
      register: 'రిజిస్టర్',
      logout: 'లాగౌట్',
      dashboard: 'డాష్‌బోర్డ్',
      matches: 'మ్యాచ్‌లు',
      myTeams: 'నా టీమ్స్',
      leaderboard: 'లీడర్‌బోర్డ్',
      profile: 'ప్రొఫైల్',
      createTeam: 'టీమ్ సృష్టించండి',
      save: 'సేవ్ చేయండి',
      cancel: 'రద్దు చేయండి',
      edit: 'సవరించండి',
      delete: 'తొలగించండి',
      back: 'వెనక్కి',
      loading: 'లోడ్ అవుతోంది...',
      error: 'లోపం',
      success: 'విజయం',
    },
    home: {
      title: 'మీ ఫాంటసీ క్రికెట్ నైపుణ్యాలను మాస్టర్ చేయండి',
      subtitle: 'ఉచిత-ఆట విద్యా వేదిక. నిజమైన డబ్బు లేదు. స్వచ్ఛమైన నైపుణ్యం.',
      getStarted: 'ఉచితంగా ప్రారంభించండి',
      learnMore: 'మరింత తెలుసుకోండి',
      whyChoose: 'REIKI ENERGY ఎందుకు ఎంచుకోవాలి?',
      freeToPlay: 'ఉచితంగా ఆడండి',
      freeToPlayDesc: 'ప్రవేశ రుసుము లేదు, నిజమైన డబ్బు లేదు. నేర్చుకోవడం మరియు సరదా కోసం ఆడండి.',
      educational: 'విద్యా వేదిక',
      educationalDesc: 'ఆర్థిక ఒత్తిడి లేకుండా ఫాంటసీ క్రికెట్ వ్యూహాలను నేర్చుకోండి.',
      realData: 'నిజమైన క్రికెట్ డేటా',
      realDataDesc: 'అధికారిక క్రికెట్ డేటా API నుండి ప్రత్యక్ష మ్యాచ్ డేటా.',
      fairPlay: 'ఫెయిర్ ప్లే హామీ',
      fairPlayDesc: 'పారదర్శక నియమాలు మరియు మోసం నిరోధక చర్యలు.',
      skillBased: 'నైపుణ్యం ఆధారిత గేమింగ్',
      skillBasedDesc: 'మీ క్రికెట్ జ్ఞానం మరియు టీమ్-నిర్మాణ నైపుణ్యాలను పరీక్షించండి.',
      community: 'పెరుగుతున్న కమ్యూనిటీ',
      communityDesc: 'వేలాది క్రికెట్ ఔత్సాహికులతో కలిసి నేర్చుకోండి.',
      howItWorks: 'ఇది ఎలా పనిచేస్తుంది',
      step1: 'ఉచితంగా రిజిస్టర్ చేయండి',
      step1Desc: 'సెకన్లలో మీ ఖాతాను సృష్టించండి. చెల్లింపు అవసరం లేదు.',
      step2: 'మ్యాచ్ ఎంచుకోండి',
      step2Desc: 'రాబోయే క్రికెట్ మ్యాచ్‌ల నుండి ఎంచుకోండి.',
      step3: 'టీమ్ నిర్మించండి',
      step3Desc: '11 ఆటగాళ్లను ఎంచుకొని కెప్టెన్ మరియు వైస్ కెప్టెన్‌ను సెట్ చేయండి.',
      step4: 'పోటీ పడండి మరియు నేర్చుకోండి',
      step4Desc: 'లీడర్‌బోర్డ్‌లో మీ ర్యాంక్‌ను చూడండి మరియు మీ నైపుణ్యాలను మెరుగుపరచుకోండి.',
    },
    auth: {
      emailPlaceholder: 'మీ ఇమెయిల్ నమోదు చేయండి',
      passwordPlaceholder: 'మీ పాస్‌వర్డ్ నమోదు చేయండి',
      namePlaceholder: 'మీ పూర్తి పేరు నమోదు చేయండి',
      phonePlaceholder: 'మీ ఫోన్ నంబర్ నమోదు చేయండి',
      loginTitle: 'తిరిగి స్వాగతం',
      loginSubtitle: 'మీ ఫాంటసీ క్రికెట్ ప్రయాణాన్ని కొనసాగించడానికి లాగిన్ చేయండి',
      registerTitle: 'ఖాతా సృష్టించండి',
      registerSubtitle: 'REIKI ENERGY లో చేరండి మరియు నేర్చుకోవడం ప్రారంభించండి',
      forgotPassword: 'పాస్‌వర్డ్ మర్చిపోయారా?',
      noAccount: 'ఖాతా లేదా?',
      haveAccount: 'ఇప్పటికే ఖాతా ఉందా?',
      signUp: 'సైన్ అప్ చేయండి',
      signIn: 'సైన్ ఇన్ చేయండి',
      ageVerification: 'నేను 18 సంవత్సరాలు లేదా అంతకంటే ఎక్కువ వయస్సు ఉన్నానని నిర్ధారిస్తున్నాను',
      acceptTerms: 'నేను నిబంధనలు మరియు షరతులను అంగీకరిస్తున్నాను',
      selectState: 'మీ రాష్ట్రాన్ని ఎంచుకోండి',
    },
    footer: {
      companyInfo: 'కంపెనీ సమాచారం',
      quickLinks: 'శీఘ్ర లింక్‌లు',
      legal: 'చట్టపరమైన',
      disclaimer: 'చట్టపరమైన నిరాకరణ',
      disclaimerText:
        'ఈ వేదిక ఆంధ్రప్రదేశ్, అస్సాం, ఒడిశా, తెలంగాణ, నాగాలాండ్ మరియు సిక్కిమ్‌లో అందుబాటులో లేదు. 18 సంవత్సరాలు మరియు అంతకంటే ఎక్కువ వయస్సు ఉన్న వినియోగదారులకు మాత్రమే అనుమతి ఉంది. ఇది నైపుణ్యం ఆధారిత, ఉచిత-ఆట వేదిక, నిజమైన డబ్బు ఉండదు.',
    },
  },
  bn: {
    common: {
      home: 'হোম',
      about: 'আমাদের সম্পর্কে',
      howToPlay: 'কীভাবে খেলবেন',
      faq: 'প্রায়শই জিজ্ঞাসিত প্রশ্ন',
      contact: 'যোগাযোগ করুন',
      terms: 'নিয়ম ও শর্তাবলী',
      privacy: 'গোপনীয়তা নীতি',
      fairPlay: 'ফেয়ার প্লে',
      responsibleGaming: 'দায়িত্বশীল গেমিং',
      login: 'লগইন',
      register: 'নিবন্ধন',
      logout: 'লগআউট',
      dashboard: 'ড্যাশবোর্ড',
      matches: 'ম্যাচ',
      myTeams: 'আমার টিম',
      leaderboard: 'লিডারবোর্ড',
      profile: 'প্রোফাইল',
      createTeam: 'টিম তৈরি করুন',
      save: 'সংরক্ষণ করুন',
      cancel: 'বাতিল করুন',
      edit: 'সম্পাদনা করুন',
      delete: 'মুছুন',
      back: 'পিছনে',
      loading: 'লোড হচ্ছে...',
      error: 'ত্রুটি',
      success: 'সফলতা',
    },
    home: {
      title: 'আপনার ফ্যান্টাসি ক্রিকেট দক্ষতা আয়ত্ত করুন',
      subtitle: 'বিনামূল্যে খেলার শিক্ষামূলক প্ল্যাটফর্ম। কোনো আসল টাকা নেই। বিশুদ্ধ দক্ষতা।',
      getStarted: 'বিনামূল্যে শুরু করুন',
      learnMore: 'আরও জানুন',
      whyChoose: 'কেন REIKI ENERGY বেছে নেবেন?',
      freeToPlay: 'বিনামূল্যে খেলুন',
      freeToPlayDesc: 'কোনো প্রবেশ ফি নেই, কোনো আসল টাকা নেই। শেখা এবং মজার জন্য খেলুন।',
      educational: 'শিক্ষামূলক প্ল্যাটফর্ম',
      educationalDesc: 'আর্থিক চাপ ছাড়াই ফ্যান্টাসি ক্রিকেট কৌশল শিখুন।',
      realData: 'আসল ক্রিকেট ডেটা',
      realDataDesc: 'অফিসিয়াল ক্রিকেট ডেটা API থেকে লাইভ ম্যাচ ডেটা।',
      fairPlay: 'ফেয়ার প্লে গ্যারান্টি',
      fairPlayDesc: 'স্বচ্ছ নিয়ম এবং প্রতারণা বিরোধী ব্যবস্থা।',
      skillBased: 'দক্ষতা ভিত্তিক গেমিং',
      skillBasedDesc: 'আপনার ক্রিকেট জ্ঞান এবং টিম-নির্মাণ দক্ষতা পরীক্ষা করুন।',
      community: 'ক্রমবর্ধমান কমিউনিটি',
      communityDesc: 'হাজার হাজার ক্রিকেট উৎসাহীদের সাথে একসাথে শিখুন।',
      howItWorks: 'এটি কীভাবে কাজ করে',
      step1: 'বিনামূল্যে নিবন্ধন করুন',
      step1Desc: 'সেকেন্ডের মধ্যে আপনার অ্যাকাউন্ট তৈরি করুন। কোনো পেমেন্ট প্রয়োজন নেই।',
      step2: 'ম্যাচ নির্বাচন করুন',
      step2Desc: 'আসন্ন ক্রিকেট ম্যাচ থেকে বেছে নিন।',
      step3: 'টিম তৈরি করুন',
      step3Desc: '11 জন খেলোয়াড় নির্বাচন করুন এবং ক্যাপ্টেন ও ভাইস ক্যাপ্টেন সেট করুন।',
      step4: 'প্রতিযোগিতা করুন এবং শিখুন',
      step4Desc: 'লিডারবোর্ডে আপনার র‍্যাঙ্ক দেখুন এবং আপনার দক্ষতা উন্নত করুন।',
    },
    auth: {
      emailPlaceholder: 'আপনার ইমেইল লিখুন',
      passwordPlaceholder: 'আপনার পাসওয়ার্ড লিখুন',
      namePlaceholder: 'আপনার পূর্ণ নাম লিখুন',
      phonePlaceholder: 'আপনার ফোন নম্বর লিখুন',
      loginTitle: 'স্বাগতম',
      loginSubtitle: 'আপনার ফ্যান্টাসি ক্রিকেট যাত্রা চালিয়ে যেতে লগইন করুন',
      registerTitle: 'অ্যাকাউন্ট তৈরি করুন',
      registerSubtitle: 'REIKI ENERGY তে যোগ দিন এবং শেখা শুরু করুন',
      forgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?',
      noAccount: 'অ্যাকাউন্ট নেই?',
      haveAccount: 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
      signUp: 'সাইন আপ করুন',
      signIn: 'সাইন ইন করুন',
      ageVerification: 'আমি নিশ্চিত করছি যে আমার বয়স 18 বছর বা তার বেশি',
      acceptTerms: 'আমি নিয়ম ও শর্তাবলী স্বীকার করি',
      selectState: 'আপনার রাজ্য নির্বাচন করুন',
    },
    footer: {
      companyInfo: 'কোম্পানির তথ্য',
      quickLinks: 'দ্রুত লিঙ্ক',
      legal: 'আইনি',
      disclaimer: 'আইনি দাবিত্যাগ',
      disclaimerText:
        'এই প্ল্যাটফর্মটি অন্ধ্র প্রদেশ, আসাম, ওড়িশা, তেলেঙ্গানা, নাগাল্যান্ড এবং সিকিমে উপলব্ধ নয়। শুধুমাত্র 18 বছর এবং তার বেশি বয়সী ব্যবহারকারীদের অনুমতি দেওয়া হয়। এটি একটি দক্ষতা ভিত্তিক, বিনামূল্যে খেলার প্ল্যাটফর্ম, কোনো আসল টাকা জড়িত নেই।',
    },
  },
};
